services:
  db:
    image: mysql
    container_name: MYSQL
    restart: unless-stopped
    ports:
      - 3010:3306
    environment:
      MYSQL_ROOT_PASSWORD: password_core_db
      MYSQL_DATABASE: core_db
    volumes:
      - ./mysql-data:/var/lib/mysql
  db2:
    image: mysql
    container_name: BI
    restart: unless-stopped
    ports:
      - 3020:3306
    environment:
      MYSQL_ROOT_PASSWORD: password_jisa_db
      MYSQL_DATABASE: bi_db
    volumes:
      - ./mysql-data2:/var/lib/mysql
